version: '3.8'

services:
    mongodb:
        image: 'mongodb/mongodb-atlas-local:latest'
        environment:
            - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-}
            - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-}
            - MONGODB_INITDB_DATABASE=product_parser
        volumes:
            - ./database/mongodb:/docker-entrypoint-initdb.d
            - 'mongodb-data:/data/db'
            - 'mongodb-configdb-data:/data/configdb'
        ports:
            - '27017:27017'
        networks:
            - product-parser-network
        healthcheck:
            test:
                - CMD
                - mongosh
                - 'mongodb://localhost:27017/admin'
                - '--eval=db.runCommand({ping:1})'
            retries: 3
            timeout: 5s
networks:
    product-parser-network:
        driver: bridge
volumes:
    mongodb-data:
        driver: local
    mongodb-configdb-data:
        driver: local
